MACOSX_DEPLOYMENT_TARGET:
- '10.9'
MACOSX_SDK_VERSION:
- '10.13'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cross_platform:
- osx-arm64
cxx_compiler:
- clang_bootstrap
cxx_compiler_version:
- '15'
llvm_version:
- '15.0'
macos_machine:
- arm64-apple-darwin20.0.0
target_platform:
- osx-64
zip_keys:
- - llvm_version
  - MACOSX_DEPLOYMENT_TARGET
- - macos_machine
  - cross_platform
zlib:
- '1.2'
